services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /opt/vaultwarden/data:/data
      - /opt/vaultwarden/certs:/certs:ro
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "https://192.168.1.60:8443"
      ROCKET_PORT: "443"
      ROCKET_TLS: '{certs="/certs/vaultwarden.crt",key="/certs/vaultwarden.key"}'
